title: Craig Tateishi
description: ようこそ　クレゴの世界へ
description_lang: ja
url: https://craig9re5.github.io
baseurl: ""
lang: en-US
avatar_url: "https://avatars.githubusercontent.com/u/200924220?s=400&u=b3885895e64a7b94b007e42ef446a49b895ede6e&v=4"
theme: jekyll-theme-cayman
show_downloads: false
permalink: pretty
markdown: kramdown
comments:
  enabled: true
  provider: giscus
  repo: craig9re5/craig9re5.github.io
  repo_id: R_kgDORiDlFg
  category: Announcements
  category_id: DIC_kwDORiDlFs4C4tf3
  mapping: pathname
  strict: 0
  reactions_enabled: 1
  emit_metadata: 0
  input_position: bottom
  theme: preferred_color_scheme
  lang: zh-CN
exclude:
  - tools
  - tmp
  - .jekyll-cache
  - _site
  - README.md
  - "*.cmd"
